apiVersion: apps/v1
kind: Deployment
metadata:
  name: interop-be-event-consumer-refactor
  namespace: dev-refactor
  labels:
    app: interop-be-event-consumer-refactor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interop-be-event-consumer-refactor
  template:
    metadata:
      labels:
        app: interop-be-event-consumer-refactor
    spec:
      serviceAccountName: interop-be-event-consumer-refactor
      containers:
        - name: interop-be-event-consumer-refactor
          image: ghcr.io/pagopa/event-consumer@$IMAGE_DIGEST
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 1.0
              memory: 2Gi
            limits:
              cpu: 1.0
              memory: 2Gi
          # TEMPORARY DISABLED - TO BE RE-ENABLED
          # livenessProbe:
          #   httpGet:
          #     path: /status
          #     port: http
          #   initialDelaySeconds: 15
          #   periodSeconds: 5
          # readinessProbe:
          #   httpGet:
          #     path: /status
          #     port: http
          #   initialDelaySeconds: 15
          #   periodSeconds: 5
          env:
            - name: HOST
              value: 0.0.0.0
            - name: PORT
              value: 3001
            - name: LOG_LEVEL
              value: info
            - name: READMODEL_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: interop-be-common-refactor
                  key: READMODEL_DB_HOST
            - name: READMODEL_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: interop-be-common-refactor
                  key: READMODEL_DB_NAME
            - name: READMODEL_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: interop-be-common-refactor
                  key: READMODEL_DB_PORT
            - name: READ_MODEL_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: read-model
                  key: REFACTOR_USERNAME
            - name: READ_MODEL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: read-model
                  key: REFACTOR_USER_PASSWORD
            - name: KAFKA_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: interop-be-catalog-consumer-refactor
                  key: KAFKA_CLIENT_ID
            - name: KAFKA_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: interop-be-catalog-consumer-refactor
                  key: KAFKA_GROUP_ID
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: interop-be-catalog-consumer-refactor
                  key: KAFKA_BROKERS
