apiVersion: apps/v1
kind: Deployment
metadata:
  name: interop-be-event-consumer-refactor
  namespace: dev-refactor
  labels:
    app: interop-be-event-consumer-refactor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interop-be-event-consumer-refactor
  template:
    metadata:
      labels:
        app: interop-be-event-consumer-refactor
    spec:
      serviceAccountName: interop-be-event-consumer-refactor
      containers:
      - name: interop-be-event-consumer-refactor
        image: ghcr.io/pagopa/event-consumer@$IMAGE_DIGEST
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 3000
            protocol: TCP
        resources:
          requests:
            cpu: 1.0
            memory: 2Gi
          limits:
            cpu: 1.0
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /status
            port: http
          initialDelaySeconds: 15
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /status
            port: http
          initialDelaySeconds: 15
          periodSeconds: 5
        env:
          - name: FOO
            value: BAR
