apiVersion: v1
kind: Service
metadata:
  name: interop-be-event-consumer-refactor
  namespace: dev-refactor
spec:
  type: ClusterIP
  ports:
    - port: 3000
      name: http
      targetPort: http
      protocol: TCP
  selector:
    app: interop-be-event-consumer-refactor

