apiVersion: apps/v1
kind: Deployment
metadata:
  name: interop-be-agreement-readmodel-writer
  namespace: dev-refactor
  labels:
    app: interop-be-agreement-readmodel-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interop-be-agreement-readmodel-writer
  template:
    metadata:
      labels:
        app: interop-be-agreement-readmodel-writer
    spec:
      serviceAccountName: interop-be-agreement-readmodel-writer
      containers:
        - name: interop-be-agreement-readmodel-writer
          image: ghcr.io/pagopa/agreement-readmodel-writer@$IMAGE_DIGEST
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1.0
              memory: 2Gi
            limits:
              cpu: 1.0
              memory: 2Gi
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "3001"
            - name: LOG_LEVEL
              value: info
            - name: READMODEL_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: interop-be-common-refactor
                  key: READMODEL_DB_HOST
            - name: READMODEL_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: interop-be-common-refactor
                  key: READMODEL_DB_NAME
            - name: READMODEL_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: interop-be-common-refactor
                  key: READMODEL_DB_PORT
            - name: SKIP_JWT_VERIFICATION
              valueFrom:
                configMapKeyRef:
                  name: interop-be-common-refactor
                  key: SKIP_JWT_VERIFICATION
            - name: WELL_KNOWN_URLS
              valueFrom:
                configMapKeyRef:
                  name: interop-be-common-refactor
                  key: WELL_KNOWN_URLS
            - name: READMODEL_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: read-model
                  key: REFACTOR_USERNAME
            - name: READMODEL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: read-model
                  key: REFACTOR_USER_PASSWORD
            - name: KAFKA_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: interop-be-agreement-readmodel-writer
                  key: KAFKA_CLIENT_ID
            - name: KAFKA_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: interop-be-agreement-readmodel-writer
                  key: KAFKA_GROUP_ID
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: interop-be-agreement-readmodel-writer
                  key: KAFKA_BROKERS
            - name: AGREEMENT_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: interop-be-agreement-readmodel-writer
                  key: AGREEMENT_TOPIC
