name: "Build & Deploy DEV"

on:
  push:
    branches:
      - 'k8s'
    # paths:
    #   - 'packages/**'
    #   - '!packages/*/scripts/**'

env:
  REGISTRY: ghcr.io

jobs:
  build_deploy_image:
    name: Build ${{ matrix.image_name }}
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - image_name: catalog-process
            dockerfile_path: packages/catalog-process
            k8s_path: packages/catalog-process/kubernetes/dev
          - image_name: event-consumer
            dockerfile_path: packages/event-consumer
            k8s_path: packages/catalog-process/kubernetes/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.image_name }}
          flavor: |
            latest=auto
            prefix=
            suffix=
          tags: |
            type=ref,event=branch
            type=ref,event=tag

      - name: Build and push Docker image
        id: build_push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: ${{ matrix.dockerfile_path }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-region: ${{ vars.AWS_REGION }}
         role-to-assume: ${{ vars.IAM_ROLE_ARN }}
         role-session-name: interop-be-monorepo-${{ github.run_number }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ vars.KUBECTL_VERSION}}

      - name: Set kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ vars.AWS_REGION }} --name ${{ vars.EKS_CLUSTER_NAME }}

      - name: Inject image digest
        working-directory: ${{ matrix.k8s_path }}
        run: |
          set -euo pipefail

          export IMAGE_DIGEST="${{ steps.build_push.outputs.digest }}"
          envsubst '$IMAGE_DIGEST' < deployment.yaml > deployment_injected.yaml
          mv deployment_injected.yaml deployment.yaml

      - name: Kubectl apply
        working-directory: ${{ matrix.k8s_path }}
        run: |
          kubectl apply -f .

