name: CI
on:
  push:
    branches: main
  pull_request:

jobs:
  format-and-lint:
    name: Format and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        with:
          run_install: true
      - uses: wearerequired/lint-action@v2
        with:
          eslint: true
          eslint_extensions: "ts,tsx"
          prettier: true
          prettier_dir: src

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        with:
          run_install: true
      - run: pnpm build
