apiVersion: apps/v1
kind: Deployment
metadata:
  name: interop-be-catalog-process-refactor
  namespace: dev-refactor
  labels:
    app: interop-be-catalog-process-refactor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interop-be-catalog-process-refactor
  template:
    metadata:
      labels:
        app: interop-be-catalog-process-refactor
    spec:
      serviceAccountName: interop-be-catalog-process-refactor
      containers:
        - name: interop-be-catalog-process-refactor
          image: ghcr.io/pagopa/catalog-process@$IMAGE_DIGEST
          imagePullPolicy: Always          
          resources:
            requests:
              cpu: 1.0
              memory: 2Gi
            limits:
              cpu: 1.0
              memory: 2Gi
          livenessProbe:
            httpGet:
              path: /status
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /status
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
          env:
            - name: PORT
              value: "3000"
            - name: HOST
              value: "0.0.0.0"
            - name: LOG_LEVEL
              value: info
            - name: MOCK_FILE_MANAGER
              valueFrom:
                configMapKeyRef:
                  name: interop-be-catalog-process-refactor
                  key: MOCK_FILE_MANAGER
            - name: EVENTSTORE_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: interop-be-common-refactor
                  key: EVENTSTORE_DB_HOST
            - name: EVENTSTORE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: interop-be-common-refactor
                  key: EVENTSTORE_DB_NAME
            - name: EVENTSTORE_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: interop-be-common-refactor
                  key: EVENTSTORE_DB_PORT
            - name: EVENTSTORE_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: persistence-management
                  key: REFACTOR_USERNAME
            - name: EVENTSTORE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: persistence-management
                  key: REFACTOR_USER_PASSWORD
            - name: EVENTSTORE_DB_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: interop-be-catalog-process-refactor
                  key: EVENTSTORE_DB_SCHEMA
            - name: EVENTSTORE_DB_USE_SSL
              valueFrom:
                configMapKeyRef:
                  name: interop-be-catalog-process-refactor
                  key: EVENTSTORE_DB_USE_SSL
            - name: READMODEL_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: interop-be-common-refactor
                  key: READMODEL_DB_HOST
            - name: READMODEL_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: interop-be-common-refactor
                  key: READMODEL_DB_NAME
            - name: READMODEL_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: interop-be-common-refactor
                  key: READMODEL_DB_PORT
            - name: SKIP_JWT_VERIFICATION
              valueFrom:
                configMapKeyRef:
                  name: interop-be-common-refactor
                  key: SKIP_JWT_VERIFICATION
            - name: WELL_KNOWN_URLS
              valueFrom:
                configMapKeyRef:
                  name: interop-be-common-refactor
                  key: WELL_KNOWN_URLS
            - name: READMODEL_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: read-model
                  key: REFACTOR_USERNAME
            - name: READMODEL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: read-model
                  key: REFACTOR_USER_PASSWORD
