apiVersion: v1
kind: Service
metadata:
  name: interop-be-catalog-process-refactor-dev
  namespace: dev-refactor
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: http
      targetPort: http
      protocol: TCP
  selector:
    app: interop-be-catalog-process-refactor-dev

