apiVersion: v1
kind: ConfigMap
metadata:
  name: interop-be-authorization-updater
  namespace: dev-refactor
data:
  KAFKA_CLIENT_ID: "dev-pagopa-interop-authorization-updater"
  KAFKA_GROUP_ID: "authorization-updater"
  KAFKA_BROKERS: "boot-yqksbq44.c3.kafka-serverless.eu-central-1.amazonaws.com:9098"
  CATALOG_TOPIC: "event-store.catalog.events,event-store.agreement.events"
  AUTHORIZATION_MANAGEMENT_URL: "interop-be-authorization-management.dev-refactor.svc.cluster.local"
  RSA_KEYS_IDENTIFIERS: "17c1177f-d7dc-4181-9f54-6fd416bf229b"
  KMS_MAX_ACQUISITION_TIMEOUT_SECONDS: 10
  GENERATED_JWT_SECONDS_TO_EXPIRE: 60
  GENERATED_JWT_ISSUER: "dev-refactor.interop.pagopa.it"
  GENERATED_JWT_SUBJECT: "dev-refactor.interop-attributes-loader"
  GENERATED_JWT_AUDIENCE: "refactor.dev.interop.pagopa.it/internal"