apiVersion: apps/v1
kind: Deployment
metadata:
  name: interop-be-authorization-updater
  namespace: dev-refactor
  labels:
    app: interop-be-authorization-updater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interop-be-authorization-updater
  template:
    metadata:
      labels:
        app: interop-be-authorization-updater
    spec:
      serviceAccountName: interop-be-authorization-updater
      containers:
        - name: interop-be-authorization-updater
          image: ghcr.io/pagopa/authorization-updater@$IMAGE_DIGEST
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 1.0
              memory: 2Gi
            limits:
              cpu: 1.0
              memory: 2Gi
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "3001"
            - name: LOG_LEVEL
              value: info
            - name: KAFKA_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: interop-be-authorization-updater
                  key: KAFKA_CLIENT_ID
            - name: KAFKA_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: interop-be-authorization-updater
                  key: KAFKA_GROUP_ID
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: interop-be-authorization-updater
                  key: KAFKA_BROKERS
            - name: KAFKA_TOPICS
              valueFrom:
                configMapKeyRef:
                  name: interop-be-authorization-updater
                  key: KAFKA_TOPICS
